# Generated by Django 4.1.5 on 2023-08-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="countries", old_name="country", new_name="name",
        ),
    ]
