# Generated by Django 4.1.5 on 2023-08-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_rename_country_countries_name"),
    ]

    operations = [
        migrations.RenameModel(old_name="Countries", new_name="Country",),
    ]
